'use strict';
// V1.4 database name, version, object store and key are deliberately unchanged.
const DB='JillsClosetDB', STORE='state', KEY='main';
const $=s=>document.querySelector(s);
const pages=['Home','Closet','Outfits','Wear','Shopping','More'];
const types=['Layer','Top','Bottom','Dress','Shoe','Accessory','Purse/Bag'];
const occasions=['Work','Casual','Going Out','Event','Travel'];
const vibes=['Edgy','Artistic','Polished','Relaxed','Minimal'];
let items=[],outfits=[],considering=[],history=[],extraState={},page='Home',draft={},suggestions=[],wearOccasion='Casual',wearVibe='',closetFilter='All',dbPromise,saveQueue=Promise.resolve();
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const uid=prefix=>prefix+'-'+(crypto.randomUUID?crypto.randomUUID():Date.now()+'-'+Math.random().toString(36).slice(2));
const button=(label,action,id='',cls='')=>`<button type="button" class="btn ${cls}" data-action="${action}" data-id="${esc(id)}">${esc(label)}</button>`;
const options=(values,selected)=>values.map(v=>`<option value="${esc(v)}" ${v===selected?'selected':''}>${esc(v)}</option>`).join('');
const category=i=>i?.type==='Shoes'?'Shoe':i?.type;
function ordered(ids){const rank={Layer:0,Top:1,Dress:1,Bottom:2,Shoe:3,Accessory:4,'Purse/Bag':5};return [...new Set(ids||[])].map(id=>items.find(i=>i.id===id)).filter(Boolean).sort((a,b)=>(rank[category(a)]??6)-(rank[category(b)]??6));}
const signature=ids=>JSON.stringify([...new Set(ids)].sort());
const coreSignature=ids=>signature(ordered(ids).filter(i=>['Layer','Top','Bottom','Dress','Shoe'].includes(category(i))).map(i=>i.id));
function dbOpen(){if(!dbPromise)dbPromise=new Promise((resolve,reject)=>{const q=indexedDB.open(DB,1);q.onupgradeneeded=()=>{if(!q.result.objectStoreNames.contains(STORE))q.result.createObjectStore(STORE)};q.onsuccess=()=>resolve(q.result);q.onerror=()=>reject(q.error);q.onblocked=()=>notify('Close other Jill’s Closet windows, then reload.');});return dbPromise;}
async function getState(){const d=await dbOpen();return new Promise((resolve,reject)=>{const q=d.transaction(STORE).objectStore(STORE).get(KEY);q.onsuccess=()=>resolve(q.result||{});q.onerror=()=>reject(q.error);});}
function save(){const snapshot=structuredClone({...extraState,items,outfits,considering,wearHistory:history,appVersion:'1.5'});const next=saveQueue.catch(()=>{}).then(async()=>{const d=await dbOpen();await new Promise((resolve,reject)=>{const tx=d.transaction(STORE,'readwrite');tx.objectStore(STORE).put(snapshot,KEY);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error||Error('Storage write aborted'));});});saveQueue=next;return next;}
async function commit(change){const before=structuredClone({items,outfits,considering,history,extraState});change();try{await save();}catch(error){({items,outfits,considering,history,extraState}=before);throw error;}}
let statusTimer;function notify(message){$('#status').textContent=message;clearTimeout(statusTimer);statusTimer=setTimeout(()=>{$('#status').textContent=''},6000);}
let modalScrollY=0,modalFocus;
function openModal(content){if($('.modal'))return;modalScrollY=window.scrollY;modalFocus=document.activeElement;document.body.classList.add('modal-open');document.body.style.top=`-${modalScrollY}px`;document.body.insertAdjacentHTML('beforeend',`<div class="modal"><section class="sheet" role="dialog" aria-modal="true" aria-labelledby="modalTitle" tabindex="-1">${content}</section></div>`);$('.sheet').focus();}
function closeModal(){$('.modal')?.remove();document.body.classList.remove('modal-open');document.body.style.top='';window.scrollTo(0,modalScrollY);modalFocus?.focus();}
function modalHead(title){return `<div class="sheet-head"><h2 id="modalTitle">${esc(title)}</h2>${button('×','close','','close-btn')}</div>`;}
function render(){closeModalIfNeeded();$('#nav').innerHTML=pages.map(p=>`<button data-action="navigate" data-id="${p}" ${p===page?'aria-current="page"':''} class="${p===page?'active':''}">${p}</button>`).join('');({Home:home,Closet:closet,Outfits:outfitsPage,Wear:wear,Shopping:shopping,More:more}[page])();}
function closeModalIfNeeded(){if($('.modal'))closeModal();}
function image(i,cls=''){return i?.imageData?`<img class="${cls}" src="${esc(safeImage(i.imageData))}" alt="${esc(i.name||i.type)}">`:`<div class="photo-placeholder ${cls}">${esc(i?.name||i?.type||'Photo unavailable')}</div>`;}
function safeImage(src){return typeof src==='string'&&(/^data:image\/(png|jpe?g|webp|gif|heic|heif);/i.test(src)||/^blob:/.test(src))?src:'';}
function pieces(ids,editable=false){return `<div class="outfit">${ordered(ids).map(i=>`<figure>${image(i)}<figcaption><span>${esc(category(i)==='Shoe'?'Shoes':category(i))}</span>${esc(i.name||i.type)}</figcaption>${editable?button('Remove','remove-piece',i.id):''}</figure>`).join('')}</div>`;}
function recentHistory(){const start=new Date();start.setHours(0,0,0,0);start.setDate(start.getDate()-13);return history.filter(h=>Number.isFinite(Date.parse(h.wornAt))&&new Date(h.wornAt)>=start&&new Date(h.wornAt)<=new Date()).sort((a,b)=>new Date(b.wornAt)-new Date(a.wornAt));}
function dateLabel(date){return new Date(date).toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'});}
function historyCard(h){return `<article class="section"><b>${esc(h.name||'My Outfit')}</b><div class="muted">${esc(dateLabel(h.wornAt))} · ${esc(h.occasion||'')}</div>${pieces(h.ids)}${h.ids.some(id=>!items.some(i=>i.id===id))?'<p class="muted">A piece in this record has been deleted.</p>':''}</article>`;}
function occasionControl(id,value){return `<label for="${id}">Occasion</label><select id="${id}">${options(occasions,value)}</select>`;}
function home(){const count=countCombinations();const recent=recentHistory();const unique=recent.filter((h,n,a)=>a.findIndex(x=>signature(x.ids)===signature(h.ids))===n).slice(0,3);$('#app').innerHTML=`<div class="home-logo"><img src="jillzcloset.png" alt="Jill’s Closet logo"></div><section class="section intro"><p class="eyebrow">Your closet, working together.</p><h1>${count.toLocaleString()} compatible outfit${count===1?'':'s'}</h1><p class="muted">Complete looks matched by occasion, color and vibe. Includes optional layers; accessories and bags are excluded.</p>${button('How is this counted?','count-info')}</section><section class="section"><h2>Let’s build today’s outfit. What’s the occasion?</h2>${occasionControl('homeOccasion',wearOccasion)}${button('Show Me What to Wear','home-wear','','primary')}</section><div class="row section-title"><h2>Recently Worn</h2>${button('View 2-Week History','history')}</div>${unique.length?unique.map(historyCard).join(''):'<div class="empty">Choose “Wore This” on an outfit to start your history.</div>'}`;}
function card(i){return `<article class="card">${image(i)}<button class="card-edit" data-action="edit-item" data-id="${esc(i.id)}" aria-label="Edit ${esc(i.name||i.type)}">Edit</button><div class="pad"><b>${esc(i.name||i.type)}</b><div class="muted">${esc(i.type)} · ${esc((i.occasions||[]).join(', '))}</div></div></article>`;}
function closet(){const active=items.filter(i=>i.active!==false&&(closetFilter==='All'||category(i)===closetFilter));$('#app').innerHTML=`<h1>Closet</h1>${!items.length?'<div class="notice"><b>Your private closet is empty.</b><p>Import your wardrobe backup or add items individually. Photos stay in this browser on this device.</p>'+button('Import Wardrobe','import')+'</div>':''}<div class="row">${button('+ Add Item','add-item','','primary')}<span class="muted">${items.filter(i=>i.active!==false).length} active items</span></div><div class="toolbar">${['All',...types].map(t=>button(t,'filter',t,t===closetFilter?'selected':'')).join('')}</div><div class="grid">${active.map(card).join('')}</div>${!active.length&&items.length?'<div class="empty">No active items in this category.</div>':''}`;}
function editItem(id){const i=items.find(x=>x.id===id);if(!i)return;openModal(`${modalHead(i.name||i.type||'Item')}<div id="editPhoto">${image(i,'edit-photo')}</div><div class="rotate-row">${button('↶ Rotate Left','rotate-left',id)}${button('Rotate Right ↷','rotate-right',id)}</div><label for="en">Name</label><input id="en" value="${esc(i.name)}"><label for="et">Category</label><select id="et">${options([...new Set([...types,category(i)])].filter(Boolean),category(i))}</select><label for="eo">Occasions (comma separated)</label><input id="eo" value="${esc((i.occasions||[]).join(', '))}"><label for="ev">Vibes (comma separated)</label><input id="ev" value="${esc((i.vibes||[]).join(', '))}"><label for="ec">Color</label><input id="ec" value="${esc(i.color)}"><label for="enn">Notes</label><textarea id="enn">${esc(i.notes)}</textarea><div class="row">${button('Save','save-item',id,'primary')}${button('Build With This','build-with',id)}${button(i.active===false?'Restore':'Archive',i.active===false?'restore':'archive',id)}${button('Delete Item','delete-item',id,'danger')}</div>`);}
const split=v=>v.split(',').map(x=>x.trim()).filter(Boolean);
async function saveEdit(id){await commit(()=>{Object.assign(items.find(i=>i.id===id),{name:$('#en').value.trim(),type:$('#et').value,occasions:split($('#eo').value),vibes:split($('#ev').value),color:$('#ec').value.trim(),notes:$('#enn').value});});render();notify('Item saved.');}
async function rotateItem(id,degrees){const i=items.find(x=>x.id===id);if(!i?.imageData)return;const img=new Image();img.src=safeImage(i.imageData);await img.decode();const c=document.createElement('canvas');c.width=img.naturalHeight;c.height=img.naturalWidth;const ctx=c.getContext('2d');ctx.translate(c.width/2,c.height/2);ctx.rotate(degrees*Math.PI/180);ctx.drawImage(img,-img.naturalWidth/2,-img.naturalHeight/2);const data=c.toDataURL('image/jpeg',.92);await commit(()=>{i.imageData=data;});$('#editPhoto').innerHTML=image(i,'edit-photo');notify('Rotation saved.');}
async function archiveItem(id,active){await commit(()=>{items.find(i=>i.id===id).active=active;});render();}
async function deleteItem(id){const i=items.find(i=>i.id===id);if(!i||!confirm(`Permanently delete “${i.name||i.type}” and its photo? It will be removed from saved outfits. Wear history will retain the date, with this piece marked as deleted. Archive keeps the item and can be undone.`))return;await commit(()=>{items=items.filter(x=>x.id!==id);outfits.forEach(o=>{o.ids=(o.ids||[]).filter(x=>x!==id)});});suggestions=[];render();notify('Item deleted.');}
function photoPick(callback){const input=$('#photoInput');input.value='';input.onchange=async e=>{const f=e.target.files[0];if(!f)return;try{if(!f.type.startsWith('image/'))throw Error('Choose an image file.');const data=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=()=>reject(r.error);r.readAsDataURL(f);});await callback(data);}catch(e){notify(e.message||'Could not save this photo.');}};input.click();}
function newItem(data,name='New item'){return {id:uid('ITEM'),name,type:'Top',imageData:data,occasions:['Casual'],vibes:[],active:true,favorite:false,lastWorn:null,timesWorn:0,notes:'',color:''};}
function addItem(){photoPick(async data=>{const i=newItem(data);await commit(()=>items.unshift(i));render();editItem(i.id);});}
function validImport(d){if(d.format!=='jills-closet-import'||!Array.isArray(d.items))throw Error('That is not a Jill’s Closet backup.');for(const i of d.items){if(!i||typeof i.id!=='string'||typeof i.type!=='string'||(i.occasions&&!Array.isArray(i.occasions))||(i.vibes&&!Array.isArray(i.vibes)))throw Error('The backup contains an invalid wardrobe item.');}for(const o of d.outfits||[]){if(!o||typeof o.id!=='string'||!Array.isArray(o.ids))throw Error('The backup contains an invalid outfit.');}for(const h of d.wearHistory||[]){if(!h||typeof h.id!=='string'||!Array.isArray(h.ids)||!Number.isFinite(Date.parse(h.wornAt)))throw Error('The backup contains an invalid wear record.');}}
function importCloset(){const input=$('#importInput');input.value='';input.onchange=async e=>{const f=e.target.files[0];if(!f)return;try{const data=JSON.parse(await f.text());validImport(data);if((items.length||outfits.length)&&!confirm('Merge this backup into your wardrobe? Existing records with the same ID will be kept.'))return;await commit(()=>{const merge=(current,added)=>{const ids=new Set(current.map(x=>x.id));for(const x of added||[])if(!ids.has(x.id)){current.push(x);ids.add(x.id);}};merge(items,data.items);merge(outfits,data.outfits);merge(history,data.wearHistory);if(!considering.length&&Array.isArray(data.considering))considering=data.considering;seedLegacyHistory();});suggestions=[];render();notify('Wardrobe and saved outfits imported.');}catch(e){notify(e.message||'Could not import this file.');}};input.click();}
function outfitsPage(){$('#app').innerHTML=`<h1>Outfits</h1><div class="row section-title">${button('+ Create Outfit','new-outfit','','primary')}<span class="muted">${outfits.length} saved</span></div>${outfits.length?outfits.map(outfitCard).join(''):'<div class="empty">No saved outfits yet. Build your first one.</div>'}`;}
function outfitCard(o){return `<article class="section"><h3>${esc(o.name||'My Outfit')}</h3><div class="muted">${esc(o.occasion||'')}${o.vibe?' · '+esc(o.vibe):''}</div>${pieces(o.ids)}<div class="row">${button('Wore This','wear-outfit',o.id)}${button('Edit','edit-outfit',o.id)}${button('Delete Outfit','delete-outfit',o.id)}</div></article>`;}
function newOutfit(prefill){draft={ids:prefill?[prefill]:[],name:'',occasion:wearOccasion,vibe:wearVibe};builder();}
function readDraft(){if($('#on'))Object.assign(draft,{name:$('#on').value,occasion:$('#oo').value,vibe:$('#ov').value});}
function builder(){$('#app').innerHTML=`<h1>${draft.id?'Edit Outfit':'Outfit Builder'}</h1><section class="section">${pieces(draft.ids,true)}<div class="row">${types.map(t=>button('+ '+t,'choose',t)).join('')}</div><label for="on">Outfit name</label><input id="on" placeholder="e.g. Polished Olive" value="${esc(draft.name||'')}">${occasionControl('oo',draft.occasion||'Casual')}<label for="ov">Vibe</label><select id="ov">${options(['',...vibes],draft.vibe||'')}</select><div class="row">${button('Save Outfit','save-outfit','','primary')}${button('Cancel','navigate','Outfits')}</div></section>`;}
function choose(type){readDraft();const active=items.filter(i=>i.active!==false&&category(i)===type&&!draft.ids.includes(i.id));openModal(`${modalHead('Choose '+type)}<div class="grid">${active.map(i=>`<button class="card choose-card" data-action="choose-piece" data-id="${esc(i.id)}">${image(i)}<span class="pad">${esc(i.name||i.type)}</span></button>`).join('')}</div>${!active.length?'<p>No additional active items in this category.</p>':''}${button('Cancel','close')}`);}
async function saveOutfit(){readDraft();if(!draft.ids.length){notify('Add at least one piece.');return;}await commit(()=>{const ids=ordered(draft.ids).map(i=>i.id);if(draft.id){const o=outfits.find(o=>o.id===draft.id);Object.assign(o,{name:draft.name||'My Outfit',ids,occasion:draft.occasion,vibe:draft.vibe});}else outfits.unshift({id:uid('O'),name:draft.name||'My Outfit',ids,occasion:draft.occasion,vibe:draft.vibe,favorite:false,lastWorn:null});});page='Outfits';render();notify('Outfit saved.');}
async function recordWear(o){if(!ordered(o.ids).length){notify('This outfit has no remaining pieces.');return;}const wornAt=new Date().toISOString();await commit(()=>{history.push({id:uid('W'),outfitId:o.id||null,name:o.name||'My Outfit',ids:ordered(o.ids).map(i=>i.id),occasion:o.occasion||wearOccasion,vibe:o.vibe||'',wornAt});if(o.id){const saved=outfits.find(x=>x.id===o.id);if(saved)saved.lastWorn=wornAt;}for(const i of ordered(o.ids)){i.lastWorn=wornAt;i.timesWorn=(Number(i.timesWorn)||0)+1;}});render();notify('Recorded in your wear history.');}
function showHistory(){const h=recentHistory();openModal(`${modalHead('Past 14 Days')}<p class="muted">Today and the previous 13 calendar days.</p>${h.length?h.map(historyCard).join(''):'<p>No outfits recorded in the past two weeks.</p>'}${button('Close','close')}`);}
function seedLegacyHistory(){for(const o of outfits){if(o.lastWorn&&Number.isFinite(Date.parse(o.lastWorn))&&!history.some(h=>h.outfitId===o.id&&h.wornAt===o.lastWorn))history.push({id:'legacy-'+o.id+'-'+o.lastWorn,outfitId:o.id,name:o.name,ids:[...(o.ids||[])],occasion:o.occasion,vibe:o.vibe,wornAt:o.lastWorn});}}
// Metadata rules are conservative heuristics, not an assertion of personal style.
const neutrals=new Set(['black','white','gray','grey','charcoal','cream','ivory','beige','tan','taupe','denim','navy','brown','camel']);
const colorFamilies={red:'warm',burgundy:'warm',maroon:'warm',pink:'warm',orange:'warm',yellow:'warm',rust:'warm',coral:'warm',green:'cool',olive:'cool',sage:'cool',blue:'cool',teal:'cool',purple:'cool',lavender:'cool'};
function colorGroup(i){const tokens=(i.color||'').toLowerCase().match(/[a-z]+/g)||[];const found=tokens.filter(t=>neutrals.has(t)||colorFamilies[t]);if(!found.length)return 'unknown';if(found.some(t=>neutrals.has(t)))return 'neutral';return colorFamilies[found[0]];}
function compatible(group){const palette=new Set(group.map(colorGroup).filter(c=>c!=='neutral'&&c!=='unknown'));if(palette.size>1)return false;const tags=group.map(i=>(i.vibes||[]).map(v=>v.toLowerCase()));if(tags.some(a=>a.includes('polished'))&&tags.some(a=>a.includes('relaxed'))&&!tags.some(a=>a.includes('polished')&&a.includes('relaxed')))return false;return true;}
function occasionMatches(i,occasion){return !(i.occasions||[]).length||(i.occasions||[]).some(o=>o.toLowerCase()===occasion.toLowerCase()||o.toLowerCase()==='all');}
function enumerate(occasion,visit){const active=items.filter(i=>i.active!==false&&!['Accessory','Purse/Bag'].includes(category(i))&&(!occasion||occasionMatches(i,occasion)));const by=t=>active.filter(i=>category(i)===t);const shoes=by('Shoe'),layers=[null,...by('Layer')],tops=by('Top'),bottoms=by('Bottom'),dresses=by('Dress');function accept(base){for(const shoe of shoes)for(const layer of layers){const group=[...(layer?[layer]:[]),...base,shoe];if(!compatible(group))continue;if(!occasion&&!occasions.some(o=>group.every(i=>occasionMatches(i,o))))continue;visit(group);}}for(const top of tops)for(const bottom of bottoms)accept([top,bottom]);for(const dress of dresses)accept([dress]);}
function countCombinations(){let count=0;enumerate(null,()=>count++);return count;}
function generate(occasion,vibe){const worn=new Map();for(const h of recentHistory())worn.set(coreSignature(h.ids),Math.max(worn.get(coreSignature(h.ids))||0,new Date(h.wornAt).getTime()));const ranked=[];enumerate(occasion,group=>{const ids=group.map(i=>i.id),last=worn.get(signature(ids))||0;const match=vibe?group.filter(i=>(i.vibes||[]).some(v=>v.toLowerCase()===vibe.toLowerCase())).length:0;const entry={ids,last,match,tie:Math.random()};ranked.push(entry);});ranked.sort((a,b)=>(Boolean(a.last)-Boolean(b.last))||(a.last-b.last)||(b.match-a.match)||(a.tie-b.tie));const chosen=[];while(chosen.length<3&&ranked.length){const unworn=ranked[0].last===0;const bestTime=ranked[0].last;let bestIndex=0,bestScore=-Infinity;for(let n=0;n<ranked.length;n++){const c=ranked[n];if(unworn&&c.last)break;if(!unworn&&c.last>bestTime)break;const overlap=chosen.reduce((s,o)=>s+c.ids.filter(id=>o.ids.includes(id)).length,0);const score=c.match*2-overlap+c.tie;if(score>bestScore){bestScore=score;bestIndex=n;}}const c=ranked.splice(bestIndex,1)[0];chosen.push({name:'Option '+(chosen.length+1),ids:c.ids,occasion,vibe});}return chosen;}
function wear(){$('#app').innerHTML=`<h1>What should I wear?</h1><section class="section">${occasionControl('wo',wearOccasion)}<label for="wv">Vibe (optional)</label><select id="wv">${options(['',...vibes],wearVibe)}</select>${button('Show 3 Outfit Options','suggest','','primary')}</section><div id="suggestion" class="wear-stage ${suggestions.length?'has-results':''}">${suggestionHTML()}</div>`;}
function suggestionHTML(){return suggestions.length?suggestions.map((o,n)=>`<section class="section"><h2>${esc(o.name)}</h2>${pieces(o.ids)}<div class="row">${button('Wore This','wear-suggestion',n)}${button('Customize & Save','customize',n)}</div></section>`).join(''):'<p class="wear-placeholder">Your next outfit starts here.</p>';}
function makeSuggestion(){wearOccasion=$('#wo').value;wearVibe=$('#wv').value;suggestions=generate(wearOccasion,wearVibe);wear();if(suggestions.length<3)notify(suggestions.length?`Only ${suggestions.length} distinct compatible look${suggestions.length===1?' is':'s are'} available for ${wearOccasion}.`:`No complete compatible looks for ${wearOccasion}. Add a top and bottom (or dress), plus shoes, with matching occasion tags.`);}
function shopping(){$('#app').innerHTML=`<h1>Shopping</h1>${button('+ Consider Item','consider','','primary')}<p class="muted">Shopping photos stay separate until you choose “Bought It.”</p>${considering.map((c,n)=>`<section class="section"><div class="row">${image(c,'thumb')}<b>${esc(c.name||'Considering item')}</b></div><div class="row">${button('Bought It — Add to Closet','promote',n)}${button('Pass','pass',n)}</div></section>`).join('')}`;}
function consider(){photoPick(async data=>{await commit(()=>considering.unshift({name:'Considering item',imageData:data,score:null}));render();});}
async function promote(n){const c=considering[n];const i=newItem(c.imageData,c.name);i.notes='Added from Shopping';await commit(()=>{items.unshift(i);considering.splice(n,1);});page='Closet';render();editItem(i.id);}
function exportData(){const blob=new Blob([JSON.stringify({...extraState,format:'jills-closet-import',version:1,appVersion:'1.5',items,outfits,considering,wearHistory:history})],{type:'application/json'});const a=document.createElement('a'),url=URL.createObjectURL(blob);a.href=url;a.download='Jills-Closet-Backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function more(){const archived=items.filter(i=>i.active===false);$('#app').innerHTML=`<h1>More</h1><section class="section"><h2>Privacy</h2><p>Your wardrobe photos, outfits and history stay in this browser’s IndexedDB on this device. The hosted app contains no personal wardrobe photos.</p><p class="muted">V1.5 · ${items.filter(i=>i.active!==false).length} active items · ${outfits.length} saved outfits</p></section><section class="section"><h2>Wear History</h2>${button('View Past 14 Days','history')}</section><section class="section"><h2>Archived Items</h2>${archived.length?archived.map(i=>`<div class="row archive-row"><span>${esc(i.name||i.type)}</span>${button('Restore','restore',i.id)}${button('Edit','edit-item',i.id)}</div>`).join(''):'<p class="muted">Nothing archived.</p>'}</section><section class="section"><h2>Backup & Import</h2><p>Export a private backup before clearing website data, changing devices or moving the app to a different address.</p><div class="row">${button('Export Private Backup','export')}${button('Import Closet File','import')}</div></section><section class="section"><h2>App Updates</h2>${button('Check for Updates','update')}</section><section class="section"><h2>Erase Local Closet</h2>${button('Erase All Local Data','erase','','danger')}</section>`;}
async function clearLocal(){if(!confirm('Erase all wardrobe items, photos, outfits, shopping items and wear history on this device? Export a private backup first.'))return;await commit(()=>{items=[];outfits=[];considering=[];history=[];extraState={};});suggestions=[];page='Home';render();}
async function action(name,id){switch(name){case 'navigate':page=id;suggestions=[];render();break;case 'close':closeModal();break;case 'home-wear':wearOccasion=$('#homeOccasion').value;page='Wear';render();makeSuggestion();break;case 'filter':closetFilter=id;closet();break;case 'add-item':addItem();break;case 'edit-item':editItem(id);break;case 'save-item':await saveEdit(id);suggestions=[];break;case 'rotate-left':await rotateItem(id,-90);break;case 'rotate-right':await rotateItem(id,90);break;case 'archive':await archiveItem(id,false);suggestions=[];break;case 'restore':await archiveItem(id,true);break;case 'delete-item':await deleteItem(id);break;case 'import':importCloset();break;case 'export':exportData();break;case 'new-outfit':newOutfit();break;case 'build-with':closeModal();page='Outfits';newOutfit(id);break;case 'edit-outfit':draft=structuredClone(outfits.find(o=>o.id===id));builder();break;case 'remove-piece':readDraft();draft.ids=draft.ids.filter(x=>x!==id);builder();break;case 'choose':choose(id);break;case 'choose-piece':if(!draft.ids.includes(id))draft.ids.push(id);closeModal();builder();break;case 'save-outfit':await saveOutfit();break;case 'delete-outfit':if(confirm('Delete this saved outfit? Wardrobe pieces and wear history will be kept.')){await commit(()=>{outfits=outfits.filter(o=>o.id!==id);});render();}break;case 'wear-outfit':await recordWear(outfits.find(o=>o.id===id));break;case 'history':showHistory();break;case 'suggest':makeSuggestion();break;case 'wear-suggestion':await recordWear(suggestions[Number(id)]);break;case 'customize':draft=structuredClone(suggestions[Number(id)]);draft.name='';page='Outfits';builder();break;case 'consider':consider();break;case 'promote':await promote(Number(id));break;case 'pass':await commit(()=>considering.splice(Number(id),1));render();break;case 'erase':await clearLocal();break;case 'count-info':openModal(`${modalHead('Compatible Outfit Count')}<p>Each look needs a top + bottom, or a dress, and shoes. A layer is optional. Pieces must share at least one occasion. Archived items, accessories and bags do not count.</p><p>Neutral colors mix freely. Recognized accent colors stay within a warm or cool palette. Separate Polished and Relaxed vibe tags are excluded unless a piece bridges both. Blank color or vibe tags are treated as flexible.</p><p>This is an estimate based on your item details, not a visual assessment of your photos. Add accurate tags to improve it. A dress takes the place of top and bottom.</p>${button('Close','close')}`);break;case 'update':if(swRegistration){await swRegistration.update();notify('Update check complete. Available updates apply automatically.');}else notify('App updates require HTTPS or localhost.');break;}}
document.addEventListener('click',async e=>{if(e.target.classList.contains('modal')){closeModal();return;}const b=e.target.closest('[data-action]');if(!b||b.disabled)return;b.disabled=true;try{await action(b.dataset.action,b.dataset.id);}catch(error){console.error(error);notify('Could not complete that change. Your saved wardrobe was kept. '+(error.message||''));}finally{b.disabled=false;}});
document.addEventListener('keydown',e=>{if(!$('.modal'))return;if(e.key==='Escape'){closeModal();return;}if(e.key==='Tab'){const nodes=[...$('.sheet').querySelectorAll('button,input,select,textarea,[tabindex="0"]')].filter(x=>!x.disabled);const first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&(document.activeElement===first||document.activeElement===$('.sheet'))){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}});
let swRegistration,swReloading=false;
async function setupSW(){if(!('serviceWorker' in navigator))return;const controlled=!!navigator.serviceWorker.controller;navigator.serviceWorker.addEventListener('controllerchange',async()=>{if(!controlled||swReloading)return;swReloading=true;notify('App updated. Reloading…');await saveQueue.catch(()=>{});location.reload();});try{swRegistration=await navigator.serviceWorker.register('./sw.js',{updateViaCache:'none'});swRegistration.addEventListener('updatefound',()=>{const worker=swRegistration.installing;worker?.addEventListener('statechange',()=>{if(worker.state==='installed'&&navigator.serviceWorker.controller)notify('A new app version is ready.');});});await swRegistration.update();}catch(e){console.warn('Offline installation unavailable',e);}}
(async()=>{try{const s=await getState();extraState={...s};items=s.items||[];outfits=s.outfits||[];considering=s.considering||[];history=s.wearHistory||[];seedLegacyHistory();render();setupSW();}catch(e){$('#app').innerHTML='<div class="notice"><h1>Your closet could not be opened</h1><p>Reload in a browser that allows local storage. No data has been erased.</p></div>';console.error(e);}})();
