const routine={0:[["Weekly reset","Review the week ahead"],["Go / Rest","Keep the day open"]],1:[["Strength · 30 min","Session 1 of 3"]],2:[["Walk","Walking day"],["Create · 15 min","Play, no finished work required"]],3:[["Strength · 30 min","Session 2 of 3"]],4:[["Walk","Walking day"],["Create · 30 min","Make something"]],5:[["Strength · 30 min","Session 3 of 3"]],6:[["Go","Free day — get out and do something"]]};
const packing={"Work gear":["Camera","Camera batteries","Battery charger","Memory cards","Tripod","Microphone","Microphone cables/accessories","Phone","Power bank","Charging cables","Laptop / tablet if needed","Work credentials","Event-specific work gear"],"Work clothing":["Work tops","Work bottoms","Undergarments","Socks","Cushioned work shoes","Indoor layer"],"Off-duty":["Relaxing clothes","Sleepwear","Travel-home outfit","Arch-support comfy shoes"],"Coffee + food":["Coffee press","Coffee beans","Water kettle","Mug","Healthy snacks","Oatmeal / breakfast","Reusable water bottle","Utensils"],"Personal":["Toiletries","Medications / supplements","Personal chargers"],"Recovery":["Foot / body recovery items"]};
const get=(k,d)=>JSON.parse(localStorage.getItem(k)??JSON.stringify(d)),set=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
function weekKey(){let d=new Date(),x=new Date(d),day=(d.getDay()+6)%7;x.setDate(d.getDate()-day);return x.toISOString().slice(0,10)}
function logs(){return get("logs-"+weekKey(),[])} function logActivity(type){let l=logs();l.push({type,date:new Date().toISOString()});set("logs-"+weekKey(),l);render()}
function logCreate(minutes){let l=logs();l.push({type:"create",minutes,date:new Date().toISOString()});set("logs-"+weekKey(),l);render()}
function counts(){let l=logs();return{strength:l.filter(x=>x.type==="strength").length,walk:l.filter(x=>x.type==="walk").length,create:l.filter(x=>x.type==="create").length}}
function render(){let d=new Date(),trip=get("tripMode",false);dateLabel.textContent=d.toLocaleDateString(undefined,{weekday:"long",month:"long",day:"numeric"});tripToggle.checked=trip;modePill.textContent=trip?"TOURNAMENT":"NORMAL";todayTitle.textContent=trip?"Tournament mode":"Your day";workLine.textContent=(d.getDay()>0&&d.getDay()<6)?"Work · 8:30 AM–12:30 PM":"No regular work block";let tasks=trip?[["Tournament day","Work + recovery; normal routine is paused"],["Packing / gear","Check what you need next"]]:routine[d.getDay()];todayTasks.innerHTML=tasks.map((t,i)=>`<div class="card task"><input type="checkbox" ${get("task-"+d.toDateString()+"-"+i,false)?"checked":""} onchange="set('task-${d.toDateString()}-${i}',this.checked)"><div><strong>${t[0]}</strong><p class="muted">${t[1]}</p></div></div>`).join("");let c=counts();strengthCount.textContent=`${Math.min(c.strength,3)}/3`;walkCount.textContent=`${Math.min(c.walk,2)}/2`;createCount.textContent=`${Math.min(c.create,2)}/2`;renderPacking()}
function renderPacking(){let state=get("packing",{});packingList.innerHTML=Object.entries(packing).map(([g,items])=>`<div class="card packgroup"><h3>${g}</h3>${items.map(item=>{let key=g+"|"+item;return `<label class="packitem"><input type="checkbox" ${state[key]?"checked":""} onchange="packCheck('${encodeURIComponent(key)}',this.checked)"><span>${item}</span></label>`}).join("")}</div>`).join("")}
function packCheck(e,v){let k=decodeURIComponent(e),s=get("packing",{});s[k]=v;set("packing",s)}function resetPacking(){if(confirm("Clear all packed items?")){set("packing",{});renderPacking()}}function toggleTrip(){set("tripMode",tripToggle.checked);render()}function saveGo(){let n=goNote.value.trim();if(!n)return;let g=get("goLog",[]);g.push({note:n,date:new Date().toISOString()});set("goLog",g);goNote.value="";alert("Saved.")}
document.querySelectorAll("nav button").forEach(b=>b.onclick=()=>{document.querySelectorAll(".view").forEach(v=>v.classList.remove("active"));document.querySelectorAll("nav button").forEach(x=>x.classList.remove("selected"));document.getElementById(b.dataset.view).classList.add("active");b.classList.add("selected")});if("serviceWorker"in navigator)navigator.serviceWorker.register("./sw.js");render();